### ISSUE TITLE
Feature request: await only future

### ISSUE THREAD

**Issue by rhalff** [google/pedantic#24]
I had to manually add [`await_only_futures`](https://dart-lang.github.io/linter/lints/await_only_futures.html) and cannot really think of a case where one would not like to do this, so perhaps add this rule by default?

**Comment by davidmorgan** [comment]
Yes, I expect `await_only_futures` will be added to `pedantic`. Just a matter of when we get around to it--a prerequisite for being in `pedantic` is that we have cleaned up all the google internal Dart code to comply, which is not always trivial :)

**Comment by rhalff** [comment]
Thanks for the answer, feel free to close this issue if it's something which will be eventually added anyway.

**Comment by davidmorgan** [comment]
Thanks. I'll leave it open in case someone else wants to request the same one :)
