### ISSUE TITLE
What does "does not reflect common usage" mean?

### ISSUE THREAD

**Issue by NatoBoram** [google/pedantic#77]
I was reading through [Unused Lints](https://github.com/google/pedantic#unused-lints) when I saw "*... does not reflect common usage*".

What does that really mean? Is it actually a deterrent for using a rule? Are the rules beneficial would it not be uncommon practice?

**Comment by davidmorgan** [comment]
'does not reflect common usage' is about style lints; it doesn't make sense to enforce a style that people are not already following themselves.

**Comment by NatoBoram** [comment]
Hi! Sorry, I think I had a brain fart, my last question unintelligible. I meant *Are the rules beneficial would it not be uncommon practice?*, I don't know where those extra words came from, haha.

For example, someone reported to have an APK reduction of a few KB <sup>negligible, I know</sup> after using `prefer_final_locals`. If it does affect some performance metrics, then it's not just about style, isn't it?

Another thing I'm wondering is why doesn't it make sense? Many, many people write different code, and some rules are followed by some people and some are not, I think it's normal. For example, it's uncommon to prefer apostrophes instead of quotes, yet there's a style lint enforcing it right [here](https://github.com/google/pedantic/blob/master/lib/analysis_options.1.9.0.yaml#L41).

**Comment by davidmorgan** [comment]
`pedantic` is about google internal linting; we had all those discussions ;) but they're not public I'm afraid.

You're welcome to point out things we might not have noticed. Smaller APK size is interesting--I would treat that as a feature request for the compiler, though, it should be the same :)

**Comment by NatoBoram** [comment]
> we had all those discussions ;) but they're not public I'm afraid

Ah, bummer. Google is full of smart people and I do enjoy reading some discussions and design pattern decisions, like the [Type Parameters - Draft Design](https://go.googlesource.com/proposal/+/refs/heads/master/design/go2draft-type-parameters.md).
