### ISSUE TITLE
Feature request: find hardcoded strings

### ISSUE THREAD

**Issue by houdayec** [google/pedantic#79]
Would it be possible to have a detection of hardcoded strings through the project. Once we have finished our project and want to internationalize it, it is painful to search for strings contained in " and ' through dozens of file.

I might be wrong, but I didn't find a proper solution to find them all easily.

**Comment by davidmorgan** [comment]
This package is just about what settings you use, for the linter itself please see the dart-lang/linter repo ... it looks like there is already a request open for what you want :)

https://github.com/dart-lang/linter/issues/2376
