### ISSUE TITLE
Remove unsafe_html

### ISSUE THREAD

**Issue by srawlins** [google/pedantic#83]
While `unsafe_html` _is_ an enabled lint at Google, it really only makes sense because of our build rules, access controls, concepts of "owners," etc.

I think users are getting more frustrated and confused by this lint rule, and the fact that you cannot `// ignore:` violations. See https://github.com/dart-lang/sdk/issues/45230 and https://github.com/dart-lang/linter/issues/2348.

I think it should be removed from the list provided in pedantic's analysis options.

**Comment by davidmorgan** [comment]
Thanks Sam.

I don't think this is the right place to fix the issue; `pedantic` isn't supposed to be anything more than the list of lints we use in google3.

@mit-mit is working on publishing separate lists which _are_ tailored for external users.

**Comment by srawlins** [comment]
The `lints` package is now published without `unsafe_html` so problem solved. 😁
