### ISSUE TITLE
Show lint warning when a late marked field is final and initialized when declaring. 

### ISSUE THREAD

**Issue by dark-chocolate** [google/pedantic#84]
In the following example, you can see the class members `a` and `b` are both initialized at the time of declaration. There's no benefit of marking them `late` as it is redundant. Can we show a lint warning here?

```dart
class Foo {
  late final int a = 0; // late is redundant
  late final int b = getB(); // late is redundant
  int getB() => 1;
}
```

**Comment by davidmorgan** [comment]
That sounds like a question for analyzer

https://github.com/dart-lang/sdk/issues/new

or linter

https://github.com/dart-lang/linter

:)

**Comment by a14n** [comment]
@dark-chocolate `late final` are lazy initialized unlike `final`. For instance try the following code in dartpad:

```dart
class A {
  late final String a = (){print('init a'); return 'a';}();
  final String b = (){print('init b'); return 'b';}();
}

main() {
  A()..a..b;
}
```

**Comment by dark-chocolate** [comment]
@davidmorgan  I'm so sorry for the wrong thread. 

@a14n Right sir, I forgot the lazy initialization usage of it.
