### ISSUE TITLE
sort_constructors_first gives false positives for factories

### ISSUE THREAD

**Issue by buttonsrtoys** [google/pedantic#85]
class Sample {
    Sample(this.answer);
    int answer;
    factory Sample.fortyTwo() => Sample(42); // <- "Sort constructor declarations before other members"
}

**Comment by bwilkerson** [comment]
According to the specification, factories are constructors, they just aren't generative constructors. I believe that the lint is working as intended.

**Comment by davidmorgan** [comment]
Please file linter things at the linter depot, `pedantic` is just about _which_ lints to enable :)

https://github.com/dart-lang/linter
